const bibles = {
    bibles_ko: [
        { bookName: '창세기', bookIndex: 1 },
        { bookName: '출애굽기', bookIndex: 2 },
        { bookName: '레위기', bookIndex: 3 },
        { bookName: '민수기', bookIndex: 4 },
        { bookName: '신명기', bookIndex: 5 },
        { bookName: '여호수아', bookIndex: 6 },
        { bookName: '사사기', bookIndex: 7 },
        { bookName: '룻기', bookIndex: 8 },
        { bookName: '사무엘상', bookIndex: 9 },
        { bookName: '사무엘하', bookIndex: 10 },
        { bookName: '열왕기상', bookIndex: 11 },
        { bookName: '열왕기하', bookIndex: 12 },
        { bookName: '역대상', bookIndex: 13 },
        { bookName: '역대하', bookIndex: 14 },
        { bookName: '에스라', bookIndex: 15 },
        { bookName: '느헤미야', bookIndex: 16 },
        { bookName: '에스더', bookIndex: 17 },
        { bookName: '욥기', bookIndex: 18 },
        { bookName: '시편', bookIndex: 19 },
        { bookName: '잠언', bookIndex: 20 },
        { bookName: '전도서', bookIndex: 21 },
        { bookName: '아가', bookIndex: 22 },
        { bookName: '이사야', bookIndex: 23 },
        { bookName: '예레미야', bookIndex: 24 },
        { bookName: '예레미야애가', bookIndex: 25 },
        { bookName: '에스겔', bookIndex: 26 },
        { bookName: '다니엘', bookIndex: 27 },
        { bookName: '호세아', bookIndex: 28 },
        { bookName: '요엘', bookIndex: 29 },
        { bookName: '아모스', bookIndex: 30 },
        { bookName: '오바댜', bookIndex: 31 },
        { bookName: '요나', bookIndex: 32 },
        { bookName: '미가', bookIndex: 33 },
        { bookName: '나훔', bookIndex: 34 },
        { bookName: '하박국', bookIndex: 35 },
        { bookName: '스바냐', bookIndex: 36 },
        { bookName: '학개', bookIndex: 37 },
        { bookName: '스가랴', bookIndex: 38 },
        { bookName: '말라기', bookIndex: 39 },
        { bookName: '마태복음', bookIndex: 40 },
        { bookName: '마가복음', bookIndex: 41 },
        { bookName: '누가복음', bookIndex: 42 },
        { bookName: '요한복음', bookIndex: 43 },
        { bookName: '사도행전', bookIndex: 44 },
        { bookName: '로마서', bookIndex: 45 },
        { bookName: '고린도전서', bookIndex: 46 },
        { bookName: '고린도후서', bookIndex: 47 },
        { bookName: '갈라디아서', bookIndex: 48 },
        { bookName: '에베소서', bookIndex: 49 },
        { bookName: '빌립보서', bookIndex: 50 },
        { bookName: '골로새서', bookIndex: 51 },
        { bookName: '데살로니가전서', bookIndex: 52 },
        { bookName: '데살로니가후서', bookIndex: 53 },
        { bookName: '디모데전서', bookIndex: 54 },
        { bookName: '디모데후서', bookIndex: 55 },
        { bookName: '디도서', bookIndex: 56 },
        { bookName: '빌레몬서', bookIndex: 57 },
        { bookName: '히브리서', bookIndex: 58 },
        { bookName: '야고보서', bookIndex: 59 },
        { bookName: '베드로전서', bookIndex: 60 },
        { bookName: '베드로후서', bookIndex: 61 },
        { bookName: '요한1서', bookIndex: 62 },
        { bookName: '요한2서', bookIndex: 63 },
        { bookName: '요한3서', bookIndex: 64 },
        { bookName: '유다서', bookIndex: 65 },
        { bookName: '요한계시록', bookIndex: 66 }
    ],
    bibles_en: [
        { bookName: 'Genesis', bookIndex: 1 },
        { bookName: 'Exodus', bookIndex: 2 },
        { bookName: 'Leviticus', bookIndex: 3 },
        { bookName: 'Numbers', bookIndex: 4 },
        { bookName: 'Deuteronomy', bookIndex: 5 },
        { bookName: 'Joshua', bookIndex: 6 },
        { bookName: 'The Book of Judges', bookIndex: 7 },
        { bookName: 'The Book of Ruth', bookIndex: 8 },
        { bookName: '1 Samuel', bookIndex: 9 },
        { bookName: '2 Samuel', bookIndex: 10 },
        { bookName: '1 Kings', bookIndex: 11 },
        { bookName: '2 Kings', bookIndex: 12 },
        { bookName: '1 Chronicles', bookIndex: 13 },
        { bookName: '2 Chronicles', bookIndex: 14 },
        { bookName: 'Ezra', bookIndex: 15 },
        { bookName: 'Nehemiah', bookIndex: 16 },
        { bookName: 'Esther', bookIndex: 17 },
        { bookName: 'The Book of Job', bookIndex: 18 },
        { bookName: 'Psalms', bookIndex: 19 },
        { bookName: 'Proverbs', bookIndex: 20 },
        { bookName: 'Ecclesiastes', bookIndex: 21 },
        { bookName: 'baby', bookIndex: 22 },
        { bookName: 'Isaiah', bookIndex: 23 },
        { bookName: 'Jeremiah', bookIndex: 24 },
        { bookName: 'Lamentations', bookIndex: 25 },
        { bookName: 'Ezekiel', bookIndex: 26 },
        { bookName: 'Daniel', bookIndex: 27 },
        { bookName: 'Hosea', bookIndex: 28 },
        { bookName: 'Joel', bookIndex: 29 },
        { bookName: 'Amos', bookIndex: 30 },
        { bookName: 'Obadiah', bookIndex: 31 },
        { bookName: 'Jonah', bookIndex: 32 },
        { bookName: 'Micah', bookIndex: 33 },
        { bookName: 'Nahum', bookIndex: 34 },
        { bookName: 'Habakkuk', bookIndex: 35 },
        { bookName: 'Zephaniah', bookIndex: 36 },
        { bookName: 'Haggai', bookIndex: 37 },
        { bookName: 'Zechariah', bookIndex: 38 },
        { bookName: 'Malachi', bookIndex: 39 },
        { bookName: 'Matthew', bookIndex: 40 },
        { bookName: 'Gospel of Mark', bookIndex: 41 },
        { bookName: 'Luke', bookIndex: 42 },
        { bookName: 'Gospel of John', bookIndex: 43 },
        { bookName: 'Acts', bookIndex: 44 },
        { bookName: 'Romans', bookIndex: 45 },
        { bookName: '1 Corinthians', bookIndex: 46 },
        { bookName: '2 Corinthians', bookIndex: 47 },
        { bookName: 'Galatians', bookIndex: 48 },
        { bookName: 'Ephesians', bookIndex: 49 },
        { bookName: 'Philippians', bookIndex: 50 },
        { bookName: 'Colossians', bookIndex: 51 },
        { bookName: '1 Thessalonians', bookIndex: 52 },
        { bookName: '2 Thessalonians', bookIndex: 53 },
        { bookName: '1 Timothy', bookIndex: 54 },
        { bookName: '2 Timothy', bookIndex: 55 },
        { bookName: 'Titus', bookIndex: 56 },
        { bookName: 'Philemon', bookIndex: 57 },
        { bookName: 'Hebrews', bookIndex: 58 },
        { bookName: 'James', bookIndex: 59 },
        { bookName: '1 Peter', bookIndex: 60 },
        { bookName: '2 Peter', bookIndex: 61 },
        { bookName: '1 John', bookIndex: 62 },
        { bookName: '2 John', bookIndex: 63 },
        { bookName: '3 John', bookIndex: 64 },
        { bookName: 'Jude', bookIndex: 65 },
        { bookName: 'Revelation', bookIndex: 66 }
    ],
    getEnBible () {
        return this.bibles_en
    },
    getKoBible () {
        return this.bibles_ko
    }
}

export default bibles